source "https://rubygems.org"

gem 'cucumber'
gem 'retriable', '~>1.4'
gem 'rspec-expectations'
gem 'rake'
gem 'colorize'

group :development do
  gem 'pry'
  gem 'rubocop'
  gem 'parallel_tests', '~>2.14.3'
  gem 'debug'
end
